### ISSUE TITLE
SwaggerUiControllerFactory error

### ISSUE THREAD

**Issue by Iraecio** [zfcampus/zf-apigility-documentation-swagger#25]
today tried to use a swagger in apigility project and found the following error.
![1](https://cloud.githubusercontent.com/assets/8146933/17074062/19417d64-5045-11e6-91d3-762966e87f8b.png)

```
/**
     * Create and return a SwaggerUiController instance.
     *
     * @param ContainerInterface $container
     * @param string $requestedName
     * @param null|array $options
     * @return SwaggerUiController
     * @throws ServiceNotCreatedException when ApiFactory service is missing.
     */
    public function __invoke(ContainerInterface $container, $requestedName, array $options = null)
    {
        if (! $container->has(ApiFactory::class)) {
            throw new ServiceNotCreatedException(sprintf(
                '%s requires the service %s, which was not found',
                SwaggerUiController::class,
                ApiFactory::class
            ));
        }

         return new SwaggerUiController($services->get(ApiFactory::class));
    }
```

I found that only this line had problem

`return new SwaggerUiController($services->get(ApiFactory::class));`

I changed `$services` to `$container` and so

`return new SwaggerUiController($container->get(ApiFactory::class));`

![2](https://cloud.githubusercontent.com/assets/8146933/17074063/194e98f0-5045-11e6-889f-486877e202f4.png)

**Comment by jamendub** [comment]
I run into the same issue here,
The fix does work, can you patch the master please ?
